name             'macbook_setup'
maintainer       'Sean Fisk'
maintainer_email 'sean@seanfisk.com'
license          'All rights reserved'
description      'Setup my personal MacBook Pro'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'homebrew'
depends          'dmg'
depends          'mac_os_x'
depends          'iterm2'
