name 'macos_setup'
maintainer 'Sean Fisk'
maintainer_email 'sean@seanfisk.com'
source_url 'https://github.com/seanfisk/personal-chef-repo'
issues_url 'https://github.com/seanfisk/personal-chef-repo/issues'
license 'Apache-2.0'
description 'Setup my personal macOS operating system'
version '0.1.0'
supports 'mac_os_x'
chef_version '~> 15'

depends 'homebrew', '~> 5.0.8'
depends 'libarchive', '~> 2.1.0'
